"use client";

import { motion } from "framer-motion";

interface ResearchReportProps {
  report: any; // Final synthesized decision
  companyName: string;
  ticker: string | null;
}

export function ResearchReport({ report, companyName, ticker }: ResearchReportProps) {
  if (!report) return null;

  const isInvest = report.verdict === "INVEST";
  const stampColorClass = isInvest ? "text-invest border-invest" : "text-pass border-pass";

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.2 }}
      className="w-full max-w-4xl mx-auto mt-16 bg-paper text-ink p-8 md:p-12 shadow-2xl relative overflow-hidden"
    >
      <div className="absolute top-0 left-0 w-full h-2 bg-brass" />

      {/* Header */}
      <div className="mb-12 border-b-2 border-ink/10 pb-8 flex flex-col md:flex-row md:items-end justify-between gap-6">
        <div>
          <h4 className="font-sans text-sm uppercase tracking-widest text-slate mb-2">Research Memorandum</h4>
          <h1 className="font-serif text-4xl md:text-5xl font-bold leading-tight">{companyName}</h1>
          {ticker && <p className="font-mono text-xl mt-2 text-slate">{ticker}</p>}
        </div>
        
        {/* The Stamp */}
        <div className="flex items-center gap-6 self-start md:self-auto">
          <div className="flex flex-col items-center">
            <span className="font-sans text-xs uppercase tracking-widest text-slate mb-1">Confidence</span>
            <div className="relative w-16 h-16 flex items-center justify-center rounded-full border-4 border-brass">
              <span className="font-mono text-xl font-bold">{report.confidenceScore}</span>
            </div>
          </div>
          <div className={`stamp text-4xl px-6 py-2 ${stampColorClass}`}>
            {report.verdict}
          </div>
        </div>
      </div>

      {/* Summary */}
      <div className="mb-12">
        <h2 className="font-sans text-sm uppercase tracking-widest text-slate mb-4">Executive Summary</h2>
        <p className="font-serif text-xl leading-relaxed">{report.summary}</p>
      </div>

      {/* Breakdown */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-12 font-sans">
        <div>
          <h3 className="text-sm uppercase tracking-widest text-slate border-b border-ink/10 pb-2 mb-4">Fundamentals</h3>
          <p className="text-ink/80 leading-relaxed">{report.reasoningBreakdown.fundamentals}</p>
        </div>
        <div>
          <h3 className="text-sm uppercase tracking-widest text-slate border-b border-ink/10 pb-2 mb-4">Sentiment & News</h3>
          <p className="text-ink/80 leading-relaxed">{report.reasoningBreakdown.sentiment}</p>
        </div>
        <div>
          <h3 className="text-sm uppercase tracking-widest text-slate border-b border-ink/10 pb-2 mb-4">Competitive Position</h3>
          <p className="text-ink/80 leading-relaxed">{report.reasoningBreakdown.competitive}</p>
        </div>
        <div>
          <h3 className="text-sm uppercase tracking-widest text-slate border-b border-ink/10 pb-2 mb-4">Key Risks</h3>
          <p className="text-ink/80 leading-relaxed">{report.reasoningBreakdown.risks}</p>
        </div>
      </div>

      <div className="mt-16 text-center text-xs text-slate font-mono uppercase tracking-widest">
        Generated by AI Investment Agent • {new Date().toLocaleDateString()}
      </div>
    </motion.div>
  );
}
